# coding: utf-8

"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.body import Body  # noqa: E501
from swagger_client.rest import ApiException


class TestBody(unittest.TestCase):
    """Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody(self):
        """Test Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body.Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
