# coding: utf-8

"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.body8 import Body8  # noqa: E501
from swagger_client.rest import ApiException


class TestBody8(unittest.TestCase):
    """Body8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody8(self):
        """Test Body8"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body8.Body8()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
