# coding: utf-8

"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_api import ServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_stats_get(self):
        """Test case for service_stats_get

        Total service stats  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
