# coding: utf-8

"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.body5 import Body5  # noqa: E501
from swagger_client.rest import ApiException


class TestBody5(unittest.TestCase):
    """Body5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody5(self):
        """Test Body5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body5.Body5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
