#!/usr/bin/env python3

import random
import sys
import os
from sty import fg
import json
import time
import getpass
import swagger_client

# temp for annoying error msg
import urllib3
urllib3.disable_warnings()


# Menu Mapping
KEY_LIST_ITEMS = 1
KEY_CONSUME_MATE = 2
KEY_CONSUME_BEER = 3
KEY_LIST_USERS = 4
KEY_INSERT_COINS = 5
KEY_CREATE_USER = 6
KEY_CREATE_ITEM = 7
KEY_HELP = 8
KEY_EXIT = 9

actions = {
    KEY_LIST_ITEMS: "Show drinks",
    KEY_CONSUME_MATE: "Consume Mate",
    KEY_CONSUME_BEER: "Consume Beer",
    KEY_LIST_USERS: "Show users",
    KEY_INSERT_COINS: "Insert coins",
    KEY_CREATE_USER: "Create user",
    KEY_CREATE_ITEM: "Create drink",
    KEY_HELP: "Help",
    KEY_EXIT: "Exit",
}

class MaaSConfig:
    def __init__(self, host, verify_ssl):
        self.host = host
        self.verify_ssl = verify_ssl

class MaaSApiClientBuilder:
    def __init__(self, config: MaaSConfig):
        super().__init__()
        self._maas_config = config

    def build_auth_api_client(self):
        # create an instance of the API class
        return swagger_client.AuthApi(swagger_client.ApiClient(self.build_config()))

    def build_items_client(self, token):
        return swagger_client.ItemsApi(swagger_client.ApiClient(self.build_config_with_token(token)))

    def build_users_client(self, token):
        return swagger_client.UsersApi(swagger_client.ApiClient(self.build_config_with_token(token)))

    def build_config(self):
        # create an configuration for the general API client
        api_client_config = swagger_client.Configuration()
        api_client_config.host = self._maas_config.host
        api_client_config.verify_ssl = self._maas_config.verify_ssl

        return api_client_config

    def build_config_with_token(self, token):
        api_client_config = swagger_client.Configuration()
        api_client_config.host = self._maas_config.host
        api_client_config.verify_ssl = self._maas_config.verify_ssl
        api_client_config.api_key = {
            'Authorization': token
        }
        api_client_config.api_key_prefix = {
            'Authorization': 'Bearer'
        }

        return api_client_config

def log(msg, serv="INFO"):
    if serv is "ERROR":
        msg = fg.red + "Error: " + msg + fg.rs
    elif serv is "SUCCESS":
        msg = fg.green + msg + fg.rs

    print(msg)

def help(auth):

    log("Available actions:")
    for key in actions.keys():
        log("[%s] %s" % (key, actions[key]))


def login():
    """
    Clear screen and show prompt
    :returns: tupel
    """
    auth_client = maas_builder.build_auth_api_client()

    os.system('clear')
    banner()
    log("Please authenticate yourself!")

    # user = input('User: ')
    # password = getpass.getpass('Password: ')
    user = "admin"
    password = "admin"

    token = None
    is_logged_in = False

    try:
        auth = auth_client.auth_login_post(user, password).to_dict()
        is_logged_in = True
    except swagger_client.rest.ApiException:
        log("Wrong username and/or password!",serv="ERROR")
        time.sleep(1)


    return is_logged_in, auth


def list_items(auth):
    items_client = maas_builder.build_items_client(auth["token"])
    log(items_client.items_get())

def list_users(auth):
    users_client = maas_builder.build_users_client(auth["token"])
    users = users_client.users_get()

    log("List of current users in the database:\n")
    log("ID\tCredits\tUsername")
    for user in users:
        user = user.to_dict()
        log("%s\t%s\t%s" % (user["id"], user["credits"], user["username"]))

def add_credits(auth):

    try:
        credits = float(input("EUR: "))
        if credits < 0 or credits > 100:
            raise ValueError
    except ValueError:
        log("Invalid input. Valid values: 1-100",serv="ERROR")
        return False

    cents = float(credits) * 100
    users_client = maas_builder.build_users_client(auth["token"])
    users_client.users_user_id_credits_add_patch(str(auth["user"]["id"]), cents)

    auth["user"]["credits"] = auth["user"]["credits"] + cents
    log("Your credit is now %.2f" % (auth["user"]["credits"] / 100), serv="SUCCESS")
    # print("EUR input can range from 1 to 100")

def create_user(auth):

    users_client = maas_builder.build_users_client(auth["token"])

    name = input("Username: ")
    admin = input("Admin? (y/n): ").lower()[0]

    if admin is 'y':
        admin = 1

    password = getpass.getpass("Password: ")
    passwordrepeat = getpass.getpass("Repeat password: ")

    try:
        users = users_client.users_post(name, password, passwordrepeat, admin)
        return True
    except:
        log("Error creating user", serv="ERROR")
        return False

def banner(auth=None):

    mate_banner = """
 __  __    _  _____ ___  __  __    _  _____
|  \/  |  / \|_   _/ _ \|  \/  |  / \|_   _|
| |\/| | / _ \ | || | | | |\/| | / _ \ | |
| |  | |/ ___ \| || |_| | |  | |/ ___ \| |
|_|  |_/_/   \_\_| \___/|_|  |_/_/   \_\_|
"""
    log(mate_banner)
    if auth is not None:
        log("Hi %s, current credits: %.2f\n" % (auth["user"]["username"], auth["user"]["credits"] / 100))

def consume_item(auth, itemid):

    cheers_msgs = [
        "Have fun!"
        "Well.. just hackspace things."
        "Nice loscher stuff <3"
        "Beer mh? How are your projects going?"
    ]

    try:
        items_client = maas_builder.build_items_client(auth["token"])
        items_client.items_item_id_consume_patch(itemid)
        log(random.choice(cheers_msgs) + " Prost!", serv="SUCCESS")
        return True
    except swagger_client.rest.ApiException:
        log("Not enough credits, dude.", serv="ERROR")
        return False
    except:
        log("Something went wrong, contact developer!")
        return False



def create_item(auth):

    name = input("Name of Drink: ")
    cost = int(input("Cost: "))

    items_client = maas_builder.build_items_client(auth["token"])

    items_client.items_post(name, cost)

    return True


def menu(auth):

    try:
        option = int(input(">>> "))
    except ValueError:
        os.system('clear')
        banner(auth)
        option = KEY_HELP

    if option == KEY_LIST_ITEMS:
        list_items(auth)
    if option == KEY_CONSUME_MATE:
        consume_item(auth, 1)
    if option == KEY_CONSUME_BEER:
        consume_item(auth, 2)
    if option == KEY_INSERT_COINS:
        add_credits(auth)
    if option == KEY_HELP:
        help(auth)

    # Admin options
    if auth["user"]["admin"] is True:
        if option == KEY_LIST_USERS:
            list_users(auth)

        if option == KEY_CREATE_USER:
            create_user(auth)

        if option == KEY_CREATE_ITEM:
            create_item(auth)

    if option == KEY_EXIT:
        return False, True

    return True, False

if __name__ == '__main__':

    maas_cfg = MaaSConfig("https://localhost:8443/v0", False)
    maas_builder = MaaSApiClientBuilder(maas_cfg)

    # This is the login loop.
    is_logged_in = False
    while is_logged_in is False:
        is_logged_in, auth = login()
        os.system('clear')
        banner(auth)
        help(auth)

        # When autenticated go to menu
        is_exit = False
        while is_exit is False:
            is_logged_in, is_exit = menu(auth)

