# coding: utf-8

"""
    MaaS

    MaaS (Matomat as a Service) API definition  # noqa: E501

    OpenAPI spec version: 0.5.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'password': 'str',
        'passwordrepeat': 'str',
        'admin': 'int'
    }

    attribute_map = {
        'name': 'name',
        'password': 'password',
        'passwordrepeat': 'passwordrepeat',
        'admin': 'admin'
    }

    def __init__(self, name=None, password=None, passwordrepeat=None, admin=None):  # noqa: E501
        """Body3 - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._password = None
        self._passwordrepeat = None
        self._admin = None
        self.discriminator = None
        self.name = name
        self.password = password
        self.passwordrepeat = passwordrepeat
        self.admin = admin

    @property
    def name(self):
        """Gets the name of this Body3.  # noqa: E501

        The name of the user  # noqa: E501

        :return: The name of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body3.

        The name of the user  # noqa: E501

        :param name: The name of this Body3.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def password(self):
        """Gets the password of this Body3.  # noqa: E501


        :return: The password of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Body3.


        :param password: The password of this Body3.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def passwordrepeat(self):
        """Gets the passwordrepeat of this Body3.  # noqa: E501


        :return: The passwordrepeat of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._passwordrepeat

    @passwordrepeat.setter
    def passwordrepeat(self, passwordrepeat):
        """Sets the passwordrepeat of this Body3.


        :param passwordrepeat: The passwordrepeat of this Body3.  # noqa: E501
        :type: str
        """
        if passwordrepeat is None:
            raise ValueError("Invalid value for `passwordrepeat`, must not be `None`")  # noqa: E501

        self._passwordrepeat = passwordrepeat

    @property
    def admin(self):
        """Gets the admin of this Body3.  # noqa: E501


        :return: The admin of this Body3.  # noqa: E501
        :rtype: int
        """
        return self._admin

    @admin.setter
    def admin(self, admin):
        """Sets the admin of this Body3.


        :param admin: The admin of this Body3.  # noqa: E501
        :type: int
        """
        if admin is None:
            raise ValueError("Invalid value for `admin`, must not be `None`")  # noqa: E501

        self._admin = admin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
